### ISSUE TITLE
README install instructions aren't user-friendly when using a recent go version

### ISSUE THREAD

**Issue by thomp** [SkynetLabs/skynet-cli#9]
Following the install instructions in the README with a recent version of go (go1.18.2 linux/amd64) doesn't proceed smoothly. Instead, invoking `go get -u github.com/SkynetLabs/skynet-cli/...` yields

    go.mod file not found in current directory or any parent directory.
            'go get' is no longer supported outside a module.

An attempt with `go install` led to complaints along the lines of

    module declares its path as: github.com/NebulousLabs/skynet-cli
            but was required as: github.com/SkynetLabs/skynet-cli

I apologize for an inability to contribute further (my familiarity with go is pretty much nonexistent).

**Comment by m-cat** [comment]
Hi @thomp, thanks for the report and sorry for the inconvenience. I'm looking into it (not a Go expert either).

**Comment by m-cat** [comment]
Pushed an attempt at a fix, we have some Gophers on the team who can review.

**Comment by m-cat** [comment]
I think this has been fixed.

**Comment by thomp** [comment]
Noted this was closed and figured I should at least pitch in and try it again given that I filed the issue. This (below) seems less than ideal but, perhaps, its some sort of issue on my end of things?

    > /usr/local/go/bin/go install github.com/SkynetLabs/skynet-cli/v2@latest
    go: downloading github.com/SkynetLabs/skynet-cli/v2 v2.1.1
    go: github.com/SkynetLabs/skynet-cli/v2@latest: module github.com/SkynetLabs/skynet-cli/v2@latest found (v2.1.1), but does not contain package github.com/SkynetLabs/skynet-cli/v2

**Comment by thomp** [comment]
That worked for me. It looks like the README has been updated as well.
